config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  resources :users do
    resources :meals, only: [:index, :show]
  end
  get '/login', to: 'sessions#new'
  resources :sessions, only: [:create]
  delete '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback' => 'users#create'
  resources :food_items do
    resources :meals, only: [:new, :create]
  end
  get '/meals/eaten_today', to: 'meals#eaten_today'
  get '/the_current_user', to: 'users#the_current_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  has_many :meals
  has_many :users, through: :meals
  validates :name, presence: true
  validates :calories, numericality: {greater_than: 0, only_integer: true}
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :food_item
  belongs_to :user
  validates :food_quantity, numericality: {greater_than: 0, only_integer: true}
  validates :user_id, presence: true
  validates :food_item_id, presence: true
  scope :eaten_today, -> {where("created_at >= ?", Time.zone.now.beginning_of_day)}

  def calorie_count
    self.food_item.calories * self.food_quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save :default_values
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  has_many :meals
  has_many :food_items, through: :meals

  def default_values
    self.max_calories ||= 2000
  end

  def todays_calories
    cal_total = 0
    if self.meals.eaten_today
      self.meals.eaten_today.each do |meal|
        cal_total += meal.calorie_count
      end
    end
    cal_total
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
    @food_items = FoodItem.all
  end

  def show
    @food_item = FoodItem.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @food_item}
    end
  end

  def new
    @food_item = FoodItem.new
  end

  def create
    @food_item = FoodItem.create(food_item_params)
    if @food_item.valid?
      redirect_to food_items_path
    else
      render :new
    end
  end

  def edit
    @food_item = FoodItem.find(params[:id])
  end

  def update
    @food_item = FoodItem.find(params[:id])
    if @food_item.update(food_item_params)
      redirect_to food_item_path(@food_item)
    else
      render :edit
    end
  end


  private

  def food_item_params
    params.require(:food_item).permit(:name, :calories)
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def new
    @meal = Meal.new(food_item_id: params[:food_item_id], user_id: session[:user_id] )
    render :new, layout: false
  end

  def create
    #fix this it's not good
    @meal = Meal.create(meal_params)
    if @meal.valid? && @meal.user_id == session[:user_id]
      render json: @meal, status: 201
    else
      render :new
    end
  end

  def index
    @user = User.find(params[:user_id])
    @meals = @user.meals
  end

  def show
    @user = User.find(params[:user_id])
    @meal = Meal.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @meal}
    end
  end

  def eaten_today
    @meals = Meal.all.eaten_today
  end

  private

  def meal_params
    params.require(:meal).permit(:description, :food_quantity, :user_id, :food_item_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if auth
      @user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
      end
      redirect_to user_path(@user)
    else
      @user = User.find_by(email: params[:user][:email])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:notice] = "Something went wrong signing in. Maybe your password is misspelled?"
        redirect_to '/login'
      end
    end
  end

  def destroy
    session.delete(:user_id) unless session[:user_id].nil?
    redirect_to '/'
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if auth
      user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex
      end
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      user = User.new(user_params)
      if user && user.save
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        flash[:notice] = "Something Went Wrong Creating This User. Maybe one with this username already exists?"
        render :new
      end
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @user}
    end
  end

  def the_current_user
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
      respond_to do |f|
        f.html {render :show}
        f.json {render json: @user}
      end
    else
      redirect_to '/'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.id == session[:user_id]
      @user.update(user_params)
      if @user && @user.save
        redirect_to user_path(@user)
      else
        flash[:notice] = "Something went wrong when editing this profile."
        render :new
      end
    else
      flash[:notice] = "You can't edit another user's profile."
      redirect_to user_path(@user)
    end
  end


  private

  def auth
    request.env['omniauth.auth']
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :max_calories)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item, url: {action: action}) do |f|%>
<div class="field">
  <strong>Name:</strong> <%= f.text_field :name %>
  <span class="right"><strong>Calories:</strong> <%= f.number_field :calories %></span>
</div>
<div class="button">
  <%= f.submit "#{button_text}" %>  
</div>
<% end %>

app/views/food_items/edit.html.erb
<% if flash[:notice] %>
<%= content_tag :div, flash[:notice] %>
<% end %>
<% if @food_item.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@food_item.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @food_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="card-header">Editing <%= @food_item.name %></div>
<%= render partial: "form", locals: {food_item: @food_item, action: "update", button_text: "Edit"} %>

app/views/food_items/index.html.erb
<div class="welcome">All Foods</div>
<div class="food-form-container">

</div>
  <% @food_items.each do |food_item| %>
  <div class="field"><%= link_to food_item.name, new_food_item_meal_path(food_item), class: "food-item-link" %> <span class="right"><strong>Calories per serving:</strong> <%= food_item.calories %></span></div>
  <% end %>
<div class="button">
<%= link_to "Add a Food Item", new_food_item_path, class: "btn btn-primary" %>
</div>
<div class="button">
<%= link_to "See what everyone's been eating", '/meals/eaten_today', class: "btn btn-primary" %>
</div>

app/views/food_items/new.html.erb
<% if flash[:notice] %>
<%= content_tag :div, flash[:notice] %>
<% end %>
<% if @food_item.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@food_item.errors.count, "error") %>
      prohibited this item from being saved:
    </h2>

    <ul>
    <% @food_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="welcome">New Food Item:</div>
<%= render partial: "form", locals: {food_item: @food_item, action: "create", button_text: "Create Food Item"} %>

app/views/food_items/show.html.erb
<div class="card-header"><%= @food_item.name %></div>
<p>Has <%= @food_item.calories %> calories.</p>
<%= link_to "Eat the #{@food_item.name}", new_food_item_meal_path(@food_item), class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calorie Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row align-items-center">
        <div class="col offset-md-1">
          <div class="main">
            <%= yield %>
          </div>
          <div class="nav">
            <strong>Calorie Tracker:</strong>
            <% if session[:user_id] %>
              <%= link_to "My Profile", user_path(session[:user_id]) %>,
            <% end %>
            Made by <a href="http://przemyslaw.org">przemyslaw.org</a>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/meals/eaten_today.html.erb
<div class="card-header">Meals Eaten Today</div>
<ul class="list-group list-group-flush">
  <% @meals.all.each do |meal| %>
    <li class="list-group-item"><%= link_to "#{meal.user.name} had #{meal.food_quantity} #{meal.food_item.name.pluralize(meal.food_quantity)}.", user_meal_path(meal.user, meal) %></li>
  <% end %>
</ul>
<%= link_to "Back", food_items_path, class: "btn btn-light" %>

app/views/meals/index.html.erb
<div class="card-header"><%= @user.name %>'s meals</div>
<ul class="list-group list-group-flush">
<% @meals.each do |meal| %>
  <li class="list-group-item"><%= meal.food_quantity %><%= link_to meal.food_item.name.pluralize(meal.food_quantity), user_meal_path(@user, meal) %></li>
<% end %>
</ul>
<div>
  <%= link_to "Back", user_path(@user), class: "btn btn-light" %>
</div>

app/views/meals/new.html.erb
<% if flash[:notice] %>
<%= content_tag :div, flash[:notice] %>
<% end %>
<% if @meal.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@meal.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @meal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="meal-form">
  <%= form_for @meal, url: {action: "create"} do |f| %>
  <div class="field">
    <strong><%= @meal.food_item.name %></strong><span class="right"><strong>Servings:</strong> <%= f.number_field :food_quantity %></span>
  </div>
  <div class="field">
    <strong>I felt:</strong> <%= f.text_field :description %>
  </div>
  <div class="button">
    <a href="#" onclick="submitMealForm();">Eat</a>
  </div>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :food_item_id %>
  <% end %>
</div>

app/views/meals/show.html.erb
<div class="card-header">
  Meal
</div>
<h1><%= @user.name %> ate <%= @meal.food_quantity %> <%= @meal.food_item.name.pluralize(@meal.food_quantity) %>.</h1>
<h3>This made <%= @user.name %> feel <%= @meal.description %>.</h3>
<%= link_to "Back", user_meals_path(@user), class: "btn btn-light" %>

app/views/users/_form.html.erb
<%= form_for(user, url: {action: action} )do |f| %>
<div class="field">
  Name: <%= f.text_field :name %>
</div>
<div class="field">
  Email: <%= f.text_field :email %>
</div>
<div class="field">
  Maximum Daily Calories: <%= f.number_field :max_calories %>
</div>
<div class="field">
  Password: <%= f.password_field :password %>   <%= f.submit "#{button_text}" %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="welcome">Edit Profile</div>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: "form", locals: {user: @user, action: "update", button_text: "Edit"} %>

app/views/users/new.html.erb
<div class="welcome">
  Create User
</div>
<% if flash[:notice] %>
<%= content_tag :div, flash[:notice] %>
<% end %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= render partial: "form", locals: {user: @user, action: "create", button_text: "Sign Up"} %>

<div class="button">
  <%= link_to "Or Login With Facebook", '/auth/facebook', class: "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
<%= content_tag :div, flash[:notice] %>
<% end %>
<div class="welcome">
  <%= @user.name %>
</div>
<div class="field">
  <strong>Calorie Limit:</strong> <%= @user.max_calories %> <span class="right"><strong>Eaten Today:</strong> <%= @user.todays_calories %></span>
</div>
<% if @user.todays_calories > @user.max_calories %>
<div class="alert alert-danger">That's over <%= @user.name %>'s limit!</div>
<% end %>
<div class="field">
  <strong>Meals Eaten Today:</strong>
</div>
<div class="meal-history">

</div>
<div class="button">
  <%= link_to "Find a food item to eat", food_items_path, class: "btn btn-primary" %>
</div>
<div class="button">
  <%= link_to "Edit Profile", edit_user_path(@user), class:"btn btn-dark" %>
</div>
<div class="button">
  <%= link_to "Log Out", '/logout', method: :delete, class: "btn btn-danger" %>
</div>